import logging
from pathlib import Path

import yaml


def load_config(yaml_file="config.yaml"):
    """
    General-purpose configuration loader with basic error handling.
    """
    config_path = Path(__file__).parent / yaml_file

    if not config_path.exists():
        logging.error(f"Config file not found: {config_path}")
        return {}

    try:
        with config_path.open("r", encoding="utf-8") as f:
            return yaml.safe_load(f) or {}
    except yaml.YAMLError as e:
        logging.error(f"Error parsing YAML: {e}")
        return {}


config = load_config()

MODEL_NAME = config["MODEL_NAME"]
MAX_TOKENS = config["MAX_TOKENS"]
FUZZ_TARGET_TEMPERATURE = config.get("FUZZ_TARGET_TEMPERATURE", config.get("TEMPERATURE", 0.5))
BLOCKER_CLASSIFIER_TEMPERATURE = config.get(
    "BLOCKER_CLASSIFIER_TEMPERATURE",
    config.get("TEMPERATURE", 0.1),
)
BLOCKER_CLASSIFIER_PARSE_RETRY_ATTEMPTS = config.get("BLOCKER_CLASSIFIER_PARSE_RETRY_ATTEMPTS", 3)
BLOCKER_CLASSIFIER_PARSE_RETRY_DELAY_SEC = config.get("BLOCKER_CLASSIFIER_PARSE_RETRY_DELAY_SEC", 2.0)
BLOCKER_TRIAGE_PARSE_MAX_RETRIES = config.get("BLOCKER_TRIAGE_PARSE_MAX_RETRIES", 2)
BLOCKER_TRIAGE_PARSE_RETRY_DELAY_SEC = config.get("BLOCKER_TRIAGE_PARSE_RETRY_DELAY_SEC", 2.0)
SEED_GENERATOR_INITIAL_TEMPERATURE = config.get("SEED_GENERATOR_INITIAL_TEMPERATURE", 0.4)
SEED_GENERATOR_LATER_TEMPERATURE = config.get(
    "SEED_GENERATOR_LATER_TEMPERATURE",
    FUZZ_TARGET_TEMPERATURE,
)
INTROSPECTOR_API_BASE_URL = config["INTROSPECTOR_API_BASE_URL"]
COVERAGE_FUZZ_TARGET_COMPILER_MAX_ATTEMPTS = config["COVERAGE_FUZZ_TARGET_COMPILER_MAX_ATTEMPTS"]
COVERAGE_ITERATION_LOOP = config["COVERAGE_ITERATION_LOOP"]
MIN_COVERAGE_IMPROVEMENT = config["MIN_COVERAGE_IMPROVEMENT"]
COVERAGE_NO_GROWTH_STOP_THRESHOLD = config["COVERAGE_NO_GROWTH_STOP_THRESHOLD"]
BLOCKER_MAX_ITERATIONS = config["BLOCKER_MAX_ITERATIONS"]
BLOCKER_FUZZ_TARGET_COMPILER_MAX_ATTEMPTS = config["BLOCKER_FUZZ_TARGET_COMPILER_MAX_ATTEMPTS"]
BLOCKER_NO_GROWTH_STOP_THRESHOLD = config["BLOCKER_NO_GROWTH_STOP_THRESHOLD"]
BLOCKER_TARGET_RUNTIME_SANITY_SECONDS = config.get("BLOCKER_TARGET_RUNTIME_SANITY_SECONDS", 10)
THINK_BUDGET_TOKEN = config["THINK_BUDGET_TOKEN"]
OLLAMA_MODEL = config.get("OLLAMA_MODEL", "qwen3:32b")
OPENROUTER_MODEL = config.get("OPENROUTER_MODEL", "qwen/qwen3-235b-a22b:free")
